<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project>

<project name="Component HIT Downloads" default="dist" basedir=".">

    <property name="cfg.prefix" value="com_" />
    <property name="cfg.name" value="hitdownloads" />
    <property name="cfg.metadata.xml" value="${cfg.name}.xml" />

    <import file="../../common/build.xml" />

</project>