<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project>

<project name="Task Plugin UpdateInschrijvingen" default="dist" basedir=".">

    <property name="cfg.prefix" value="plg_task_" />
    <property name="cfg.name" value="updateinschrijvingen" />
    <property name="cfg.metadata.xml" value="${cfg.name}.xml" />

    <import file="../../../common/build.xml" />

</project>