services:

  joomla:
    # image: joomla:5
    image: hit_dev_docker_j5:latest
    container_name: hit_joomla
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: secret
      JOOMLA_DB_NAME: joomla_db
      JOOMLA_SITE_NAME: HIT Joomla 5 DEV
      JOOMLA_ADMIN_USER: Joomla Admin
      JOOMLA_ADMIN_USERNAME: admin
      JOOMLA_ADMIN_PASSWORD: adminadminadmin
      JOOMLA_ADMIN_EMAIL: kampinfo@hit.scouting.nl
    volumes:
      - hit-j5-joomla-data:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - joomla_network

  db:
    image: mysql:8.1
    container_name: hit_joomla_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - hit-j5-mysql-data:/var/lib/mysql
    networks:
      - joomla_network

volumes:
  hit-j5-joomla-data:
  hit-j5-mysql-data:

networks:
  joomla_network:
