version: "3.7"

services:
  joomla:
    image: mdo-php80-joomla310:latest
    ports:
      - 80:80
    volumes:
      - hit-joomla-data:/var/www/html
    links:
      - joomladb:mysql
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: secret
      JOOMLA_DB_NAME: hit_joomla_db

  joomladb:
    image: mysql:5.7
    volumes:
      - hit-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hit_joomla_db

volumes:
  hit-joomla-data:
  hit-mysql-data:
