[
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3098
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "Alphen Team X-perience"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 13
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 54
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 3
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3106
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "Back 2 Basic"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 13
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 24
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 1
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3100
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "Brainiegek"
, "kampinfo_camp_isouder": 0
, "frm_price": 37
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 0
, "frm_part_min_ct": 12
, "frm_part_max_ct": 30
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3108
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "GPS-hike (Grote Paas Speurtocht)"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 18
, "frm_max_age": 88
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 50
, "frm_max_outof_group": 15
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 5
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3101
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "Het E.E.J.E.H Kamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 15
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 0
, "frm_part_min_ct": 6
, "frm_part_max_ct": 40
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3105
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "HIT Kamperen"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 20
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 10
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3102
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "Ouder-Kind Hike"
, "kampinfo_camp_isouder": 1
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "17:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 50
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3099
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "The Challenge"
, "kampinfo_camp_isouder": 0
, "frm_price": 37
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 14
, "frm_max_age": 18
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 60
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3107
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2014"
, "frm_nm": "ThemaHIT"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 11
, "frm_max_age": 14
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 25
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3119
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2014"
, "frm_nm": "\"De Gulden Hike 2\""
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 14
, "frm_max_age": 17
, "frm_min_age_margin_days": 30
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 18
, "frm_part_max_ct": 30
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 15
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3117
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2014"
, "frm_nm": "Do Dare Deal: Black & White, the final edition"
, "kampinfo_camp_isouder": 0
, "frm_price": 67
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "20:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "13:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 18
, "frm_max_age": 27
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 40
, "frm_max_outof_group": 8
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 5
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3118
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2014"
, "frm_nm": "Niet Zomaar Een HIT"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "11:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 16
, "frm_max_age": 88
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 80
, "frm_max_outof_group": 80
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 80
, "fte_parts_min_ct": 0
, "fte_parts_max_ct": 0
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3120
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2014"
, "frm_nm": "Ouder kind hike Baarn"
, "kampinfo_camp_isouder": 1
, "frm_price": 52
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 50
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 2
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3114
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2014"
, "frm_nm": "Rank (H)IT"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "11:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 16
, "frm_max_age": 88
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 80
, "frm_max_outof_group": 99
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 99
, "fte_parts_min_ct": 0
, "fte_parts_max_ct": 0
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3116
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2014"
, "frm_nm": "Welp - Ouder Avonturenkamp"
, "kampinfo_camp_isouder": 1
, "frm_price": 52
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3133
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Adventure Rangers"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "13:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 32
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3131
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Beginnershike"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:30"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 9
, "frm_max_age": 12
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 30
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 15
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3126
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Brownsea Camp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:30"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 13
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 25
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3136
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Expeditie Dwingeloo"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "13:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 11
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 12
, "frm_part_max_ct": 32
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 16
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3125
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Happyhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "13:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 14
, "frm_max_age": 18
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 40
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3135
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Jongerenhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "14:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "18:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 18
, "frm_max_age": 50
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 40
, "frm_part_max_ct": 150
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 15
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3127
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Junior Zwerfhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "13:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 9
, "frm_max_age": 13
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 32
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 18
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3123
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Kokkamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "18:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 13
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 40
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3134
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Ouder-Kind Hike Dwingeloo"
, "kampinfo_camp_isouder": 1
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 7
, "frm_max_age": 55
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 54
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 27
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3124
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Trapperskamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "13:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "18:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 16
, "frm_part_max_ct": 40
, "frm_max_outof_group": 8
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 20
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3132
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Triathike"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 14
, "frm_max_age": 18
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 36
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3128
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Vrije Zwerfhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 37
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "13:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 15
, "frm_max_age": 21
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 200
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 30
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3129
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Woodcamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "13:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 11
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 12
, "frm_part_max_ct": 25
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 10
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3130
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2014"
, "frm_nm": "Zwerfhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "13:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 16
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 86
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3147
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Adventure Trail"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 41
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 20
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3142
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "AppTrail 4.0"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "11:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 17
, "frm_max_age": 19
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 75
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3137
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Groepshike"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 50
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 8
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3151
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "HIK (Hike Interesse Kamp)"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 26
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3143
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Kokkamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 11
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 40
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3138
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Koninklijke Survival Expeditie Harderwijk"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "11:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 16
, "frm_max_age": 32
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 12
, "frm_part_max_ct": 40
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3145
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "LAN HIT"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 14
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 20
, "frm_max_outof_group": 5
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 0
, "fte_parts_max_ct": 0
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3141
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Op zoek naar..."
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 7
, "frm_max_age": 9
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 28
, "frm_max_outof_group": 5
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 0
, "fte_parts_max_ct": 0
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3154
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Ouder Kind Hike"
, "kampinfo_camp_isouder": 1
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 7
, "frm_max_age": 60
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 0
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3140
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Pio-Extreme"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 16
, "frm_max_age": 19
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 30
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 30
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3139
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Piokamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 11
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 25
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 15
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3148
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Ruiterkamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 72
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 16
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 12
, "frm_part_max_ct": 16
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3150
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Ruiterkamp Gevorderden"
, "kampinfo_camp_isouder": 0
, "frm_price": 72
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 16
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 8
, "frm_part_max_ct": 8
, "frm_max_outof_group": 2
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3152
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "TecHIT"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 14
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 24
, "frm_part_max_ct": 30
, "frm_max_outof_group": 3
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3146
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2014"
, "frm_nm": "Woudlopershike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 20
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 10
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3083
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "De Aller-slechtste HIT van NL"
, "kampinfo_camp_isouder": 0
, "frm_price": 62
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 14
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 40
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 15
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3092
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "Deutschland Dropping Race"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 14
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 18
, "frm_part_max_ct": 42
, "frm_max_outof_group": 8
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3090
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "Eifel 50° Noord - Worst Case Scenario"
, "kampinfo_camp_isouder": 0
, "frm_price": 82
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "09:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 15
, "frm_max_age": 18
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 40
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3153
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "En da's állemaal in de Eifel gebeurd?!"
, "kampinfo_camp_isouder": 0
, "frm_price": 82
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 13
, "frm_max_age": 16
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 40
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3097
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "Ghana Express"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 11
, "frm_max_age": 16
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 99
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3089
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "InterHITy"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "11:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 18
, "frm_max_age": 30
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 16
, "frm_part_max_ct": 40
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 12
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3085
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "Make Your Choice"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "19:15"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 14
, "frm_max_age": 16
, "frm_min_age_margin_days": 99
, "frm_max_age_margin_days": 99
, "frm_part_min_ct": 25
, "frm_part_max_ct": 50
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3091
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "Powerkids HIT-it"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 24
, "frm_part_max_ct": 32
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3093
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2014"
, "frm_nm": "Stookkamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 18
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 40
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3110
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2014"
, "frm_nm": "Bourgondische Autopuzzeltocht"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:30"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 23
, "frm_max_age": 65
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 15
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 5
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3111
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2014"
, "frm_nm": "Game Time"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 13
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 50
, "frm_max_outof_group": 20
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 30
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3112
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2014"
, "frm_nm": "TeCoHit"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "12:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 10
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 24
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3122
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2014"
, "frm_nm": "Treasure Hunt 3.0"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "10:30"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 13
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 30
, "frm_max_outof_group": 8
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 15
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 3
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2014
, "kampinfo_camp_id": 3109
, "kampinfo_project_evenement_id": 4217
, "frm_cancel_dt1_day": 23
, "frm_cancel_dt1_month": "maart"
, "frm_cancel_dt1_year": 2014
, "frm_cancel_dt2_day": 23
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2014
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2014
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2014"
, "frm_nm": "Waar rook is ... is vuur"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 19
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2014
, "frm_from_time": "09:00"
, "frm_till_dt_day": 21
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2014
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2014
, "frm_book_till_dt_day": 23
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2014
, "frm_min_age": 12
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 25
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
]