[
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3174
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "Alphen Team X-perience"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 13
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 60
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 14
, "fte_parts_min_ct": 3
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3167
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "GPS-hike (Grote Paas Speurtocht)"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 18
, "frm_max_age": 88
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 50
, "frm_max_outof_group": 15
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 5
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3171
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "Het E.E.J.E.H Kamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 10
, "frm_max_age": 15
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 0
, "frm_part_min_ct": 6
, "frm_part_max_ct": 40
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3222
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "HIT leren organiseren"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 18
, "frm_max_age": 30
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 99
, "frm_part_min_ct": 6
, "frm_part_max_ct": 15
, "frm_max_outof_group": 2
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 2
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3221
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "Houthak- & Natuurbeheerderskamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 14
, "frm_max_age": 17
, "frm_min_age_margin_days": 30
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 15
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3172
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "Ouder-Kind-Hike"
, "kampinfo_camp_isouder": 1
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "17:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 50
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3175
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "The Challenge"
, "kampinfo_camp_isouder": 0
, "frm_price": 37
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 14
, "frm_max_age": 18
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 60
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3223
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "The Junior Challenge"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 14
, "frm_min_age_margin_days": 30
, "frm_max_age_margin_days": 30
, "frm_part_min_ct": 16
, "frm_part_max_ct": 24
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 6
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3168
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Alphen"
, "projectcode": "HIT ALPHEN 2015"
, "frm_nm": "ThemaHIT"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 14
, "frm_min_age_margin_days": 10
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 25
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3181
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2015"
, "frm_nm": "\"De Gulden Hike\""
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 14
, "frm_max_age": 18
, "frm_min_age_margin_days": 30
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 36
, "frm_max_outof_group": 36
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 18
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3216
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2015"
, "frm_nm": "CSI: Crime Scout Investigation"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 15
, "frm_max_age": 18
, "frm_min_age_margin_days": 7
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 30
, "frm_max_outof_group": 5
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 5
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3179
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2015"
, "frm_nm": "Do, Dare & Deal with it! meets Scouts"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 15
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 40
, "frm_max_outof_group": 8
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 5
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3176
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2015"
, "frm_nm": "Go for  (H)IT!!"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "11:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 16
, "frm_max_age": 88
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 80
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 80
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 80
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3180
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2015"
, "frm_nm": "Niet Zomaar Een HIT"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "11:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 16
, "frm_max_age": 88
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 80
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 80
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 80
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3177
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2015"
, "frm_nm": "Ouder-Kind-Hike Baarn"
, "kampinfo_camp_isouder": 1
, "frm_price": 52
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 30
, "frm_part_max_ct": 50
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 2
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3178
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2015"
, "frm_nm": "Welp-Ouder-Avonturenkamp"
, "kampinfo_camp_isouder": 1
, "frm_price": 52
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 7
, "frm_max_age": 10
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3225
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Baarn"
, "projectcode": "HIT BAARN 2015"
, "frm_nm": "Wie is De Mol?"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "11:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 0
, "frm_part_min_ct": 10
, "frm_part_max_ct": 20
, "frm_max_outof_group": 2
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 20
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 2
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3192
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Adventure Rangers"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 32
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3190
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Beginnershike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:30"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 9
, "frm_max_age": 12
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 30
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 15
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3185
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Brownsea Camp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:30"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 13
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 25
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3195
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Expeditie Dwingeloo"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 12
, "frm_part_max_ct": 32
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 16
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3184
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Happyhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 14
, "frm_max_age": 18
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 40
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3194
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Jongerenhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "14:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "18:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 18
, "frm_max_age": 50
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 40
, "frm_part_max_ct": 100
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 15
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3186
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Junior Zwerfhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 9
, "frm_max_age": 13
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 32
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 18
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3182
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Kokkamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "18:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 10
, "frm_max_age": 13
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 40
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3193
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Ouder-Kind-Hike Dwingeloo"
, "kampinfo_camp_isouder": 1
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "18:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 7
, "frm_max_age": 55
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 50
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3183
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Trapperskamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "18:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 16
, "frm_part_max_ct": 40
, "frm_max_outof_group": 8
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 20
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3191
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Triathike"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 14
, "frm_max_age": 18
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 36
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3187
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Vrije Zwerfhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 37
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 15
, "frm_max_age": 21
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 120
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 30
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3188
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Woodcamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 12
, "frm_part_max_ct": 25
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 10
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3189
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Dwingeloo"
, "projectcode": "HIT DWINGELOO 2015"
, "frm_nm": "Zwerfhike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 16
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 86
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3205
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Adventure Trail"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 41
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 20
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3201
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "AppTrail 4.0"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 17
, "frm_max_age": 21
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 6
, "frm_part_max_ct": 35
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3196
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Groepshike"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 17
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 1
, "frm_part_min_ct": 30
, "frm_part_max_ct": 50
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 3
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3208
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "HIK (Hike Interesse Kamp)"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 10
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 26
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3220
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Hoe Overleef Ik?!"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 9
, "frm_max_age": 12
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 18
, "frm_part_max_ct": 35
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3197
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Koninklijke Survival Expeditie Harderwijk"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "11:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 16
, "frm_max_age": 36
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 12
, "frm_part_max_ct": 40
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3202
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Kookkamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 24
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3203
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "LAN HIT"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 14
, "frm_max_age": 19
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 20
, "frm_max_outof_group": 5
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 20
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 20
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3200
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Op zoek naar..."
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 7
, "frm_max_age": 9
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 28
, "frm_max_outof_group": 5
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 28
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 28
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3210
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Ouder-Kind-Hike"
, "kampinfo_camp_isouder": 1
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 7
, "frm_max_age": 60
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 0
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3199
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Pio-Extreme"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 15
, "frm_max_age": 20
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 10
, "frm_part_max_ct": 30
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 30
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3198
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Piokamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 35
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 20
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3206
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Ruiterkamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 82
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 16
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 12
, "frm_part_max_ct": 16
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3207
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Ruiterkamp Gevorderden"
, "kampinfo_camp_isouder": 0
, "frm_price": 82
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "17:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 16
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 8
, "frm_part_max_ct": 8
, "frm_max_outof_group": 2
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 2
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3204
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Harderwijk"
, "projectcode": "HIT HARDERWIJK 2015"
, "frm_nm": "Woudlopershike"
, "kampinfo_camp_isouder": 0
, "frm_price": 42
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 5
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 10
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3164
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "BeverHIT"
, "kampinfo_camp_isouder": 0
, "frm_price": 32
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "13:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 5
, "frm_max_age": 7
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 36
, "frm_max_outof_group": 5
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 7
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 5
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3155
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "Deutschland Dropping Race"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 14
, "frm_max_age": 17
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 18
, "frm_part_max_ct": 42
, "frm_max_outof_group": 8
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 21
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3161
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "Eifel 50° Noord - Hunger Games"
, "kampinfo_camp_isouder": 0
, "frm_price": 82
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "09:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 15
, "frm_max_age": 18
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 25
, "frm_part_max_ct": 40
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3163
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "En da's állemæl in de Eifål gebørd?!"
, "kampinfo_camp_isouder": 0
, "frm_price": 82
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 13
, "frm_max_age": 16
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 37
, "frm_part_max_ct": 45
, "frm_max_outof_group": 0
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 4
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3159
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "HITernational"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 15
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 0
, "frm_part_min_ct": 30
, "frm_part_max_ct": 42
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 21
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 2
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3160
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "InterHITy"
, "kampinfo_camp_isouder": 0
, "frm_price": 57
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "11:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 18
, "frm_max_age": 30
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 16
, "frm_part_max_ct": 44
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 12
, "fte_parts_min_ct": 3
, "fte_parts_max_ct": 4
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3158
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "Make Your Choice"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "19:15"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 14
, "frm_max_age": 17
, "frm_min_age_margin_days": 99
, "frm_max_age_margin_days": 99
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 11
, "fte_parts_min_ct": 3
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3162
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "Powerkids HIT-it"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 7
, "frm_max_age": 11
, "frm_min_age_margin_days": 0
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 24
, "frm_part_max_ct": 32
, "frm_max_outof_group": 6
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3156
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "Stookkamp"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 10
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 40
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3166
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Mook"
, "projectcode": "HIT MOOK 2015"
, "frm_nm": "Zeilhit '15"
, "kampinfo_camp_isouder": 0
, "frm_price": 62
, "frm_from_dt_day": 3
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "20:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 11
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 21
, "frm_part_max_ct": 25
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 4
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3212
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2015"
, "frm_nm": "Bourgondische Autopuzzeltocht"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:30"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 23
, "frm_max_age": 65
, "frm_min_age_margin_days": 99
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 50
, "frm_max_outof_group": 15
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 5
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3213
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2015"
, "frm_nm": "Game Time"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "10:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "16:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 10
, "frm_max_age": 13
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 40
, "frm_max_outof_group": 20
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 30
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 6
, "fte_modulo": 0
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3214
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2015"
, "frm_nm": "TeCoHit"
, "kampinfo_camp_isouder": 0
, "frm_price": 52
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "12:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "14:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 10
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 20
, "frm_part_max_ct": 24
, "frm_max_outof_group": 4
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 0
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3215
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2015"
, "frm_nm": "Treasure Hunt 3.0"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "11:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 13
, "frm_max_age": 15
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 35
, "frm_max_outof_group": 8
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 18
, "fte_parts_min_ct": 2
, "fte_parts_max_ct": 3
, "fte_modulo": 1
},
{ "kampinfo_project_jaar": 2015
, "kampinfo_camp_id": 3211
, "kampinfo_project_evenement_id": 5022
, "frm_cancel_dt1_day": 1
, "frm_cancel_dt1_month": "januari"
, "frm_cancel_dt1_year": 2015
, "frm_cancel_dt2_day": 8
, "frm_cancel_dt2_month": "maart"
, "frm_cancel_dt2_year": 2015
, "kampinfo_project_inningsdatum_day": 1
, "kampinfo_project_inningsdatum_month": "januari"
, "kampinfo_project_inningsdatum_year": 2015
, "frm_location_nm": "Zeeland"
, "projectcode": "HIT ZEELAND 2015"
, "frm_nm": "Waar rook is ... is vuur"
, "kampinfo_camp_isouder": 0
, "frm_price": 47
, "frm_from_dt_day": 4
, "frm_from_dt_month": "april"
, "frm_from_dt_year": 2015
, "frm_from_time": "09:00"
, "frm_till_dt_day": 6
, "frm_till_dt_month": "april"
, "frm_till_dt_year": 2015
, "frm_till_time": "15:00"
, "frm_book_from_dt_day": 2
, "frm_book_from_dt_month": "januari"
, "frm_book_from_dt_year": 2015
, "frm_book_till_dt_day": 8
, "frm_book_till_dt_month": "maart"
, "frm_book_till_dt_year": 2015
, "frm_min_age": 12
, "frm_max_age": 14
, "frm_min_age_margin_days": 90
, "frm_max_age_margin_days": 90
, "frm_part_min_ct": 15
, "frm_part_max_ct": 30
, "frm_max_outof_group": 10
, "fte_teams_min_ct": 0
, "fte_teams_max_ct": 25
, "fte_parts_min_ct": 1
, "fte_parts_max_ct": 3
, "fte_modulo": 0
},
]