[
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 526
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "Alphen Team X-perience"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 13
, frm_max_age: 17
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 20
, frm_part_max_ct: 54
, frm_max_outof_group: 6
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 3
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 523
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "Back 2 Basic"
, frm_price: 47
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 10
, frm_max_age: 13
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 24
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 1
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 525
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "GPS-hike (Grote Paas Speurtocht)"
, frm_price: 47
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 18
, frm_max_age: 88
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 50
, frm_max_outof_group: 15
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 5
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 522
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "HIT Kamperen"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 14
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 20
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 10
, fte_parts_min_ct: 2
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 519
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "Ouder-Kind Hike"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "17:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 7
, frm_max_age: 55
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 50
, frm_max_outof_group: 10
, fte_teams_min_ct: 0
, fte_teams_max_ct: 25
, fte_parts_min_ct: 2
, fte_parts_max_ct: 2
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 521
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "Pionieren"
, frm_price: 47
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "16:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 15
, frm_max_age: 18
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 35
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 5
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 518
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "Pleisterkamp"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 11
, frm_max_age: 13
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 0
, frm_part_min_ct: 6
, frm_part_max_ct: 40
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 520
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "Snelverbandkamp"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 13
, frm_max_age: 15
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 0
, frm_part_min_ct: 6
, frm_part_max_ct: 20
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 517
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "Ster, Weer en Meer"
, frm_price: 37
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 10
, frm_max_age: 15
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 0
, frm_part_min_ct: 12
, frm_part_max_ct: 30
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 516
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "The Challenge"
, frm_price: 37
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 14
, frm_max_age: 18
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 90
, frm_part_min_ct: 25
, frm_part_max_ct: 40
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 524
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Alphen"
, fld_led_id: 83
, frm_nm: "ThemaHIT"
, frm_price: 37
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 11
, frm_max_age: 14
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 25
, frm_max_outof_group: 10
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 527
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Baarn"
, fld_led_id: 86
, frm_nm: "\"De Gulden Hike\""
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "10:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 11
, frm_max_age: 15
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 90
, frm_part_min_ct: 20
, frm_part_max_ct: 42
, frm_max_outof_group: 6
, fte_teams_min_ct: 0
, fte_teams_max_ct: 20
, fte_parts_min_ct: 2
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 532
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Baarn"
, fld_led_id: 86
, frm_nm: "50 Tinten HIT"
, frm_price: 52
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "11:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 16
, frm_max_age: 88
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 50
, frm_part_max_ct: 80
, frm_max_outof_group: 99
, fte_teams_min_ct: 0
, fte_teams_max_ct: 99
, fte_parts_min_ct: 0
, fte_parts_max_ct: 0
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 528
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Baarn"
, fld_led_id: 86
, frm_nm: "Do, dare and deal with it! The Wanted!"
, frm_price: 62
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "20:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "13:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 17
, frm_max_age: 23
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 25
, frm_part_max_ct: 50
, frm_max_outof_group: 8
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 5
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 529
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Baarn"
, fld_led_id: 86
, frm_nm: "Niet Zomaar Een HIT"
, frm_price: 57
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "11:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "16:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 16
, frm_max_age: 88
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 60
, frm_part_max_ct: 80
, frm_max_outof_group: 80
, fte_teams_min_ct: 0
, fte_teams_max_ct: 80
, fte_parts_min_ct: 0
, fte_parts_max_ct: 0
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 530
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Baarn"
, fld_led_id: 86
, frm_nm: "VIS & KO(ken)"
, frm_price: 72
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "20:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 16
, frm_max_age: 88
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 18
, frm_part_max_ct: 26
, frm_max_outof_group: 6
, fte_teams_min_ct: 0
, fte_teams_max_ct: 13
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 531
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Baarn"
, fld_led_id: 86
, frm_nm: "Welp - Ouder Avonturenkamp"
, frm_price: 47
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "10:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 7
, frm_max_age: 11
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 20
, frm_part_max_ct: 50
, frm_max_outof_group: 6
, fte_teams_min_ct: 0
, fte_teams_max_ct: 25
, fte_parts_min_ct: 2
, fte_parts_max_ct: 2
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 556
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Adventure Rangers"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "13:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 7
, frm_max_age: 11
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 32
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 3
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 565
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Beginnershike"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:30"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 9
, frm_max_age: 12
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 30
, frm_max_outof_group: 6
, fte_teams_min_ct: 0
, fte_teams_max_ct: 15
, fte_parts_min_ct: 2
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 560
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Brownsea Camp"
, frm_price: 47
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "10:30"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 13
, frm_max_age: 17
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 25
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 552
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Expeditie Dwingeloo"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "13:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 11
, frm_max_age: 14
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 12
, frm_part_max_ct: 32
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 16
, fte_parts_min_ct: 2
, fte_parts_max_ct: 2
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 559
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Happyhike"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "13:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 14
, frm_max_age: 18
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 40
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 554
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Jongerenhike"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "14:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "18:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 18
, frm_max_age: 50
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 40
, frm_part_max_ct: 150
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 15
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 561
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Junior Zwerfhike"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "13:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 9
, frm_max_age: 13
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 20
, frm_part_max_ct: 41
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 18
, fte_parts_min_ct: 2
, fte_parts_max_ct: 3
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 557
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Kokkamp"
, frm_price: 47
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "18:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 10
, frm_max_age: 13
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 25
, frm_part_max_ct: 40
, frm_max_outof_group: 6
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 3
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 553
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Ouder-kindhike"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 7
, frm_max_age: 55
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 54
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 27
, fte_parts_min_ct: 2
, fte_parts_max_ct: 2
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 558
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Trapperskamp"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "13:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "18:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 15
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 16
, frm_part_max_ct: 40
, frm_max_outof_group: 8
, fte_teams_min_ct: 0
, fte_teams_max_ct: 20
, fte_parts_min_ct: 2
, fte_parts_max_ct: 3
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 555
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Triathike"
, frm_price: 47
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 14
, frm_max_age: 18
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 36
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 562
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Vrije Zwerfhike"
, frm_price: 37
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "13:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 15
, frm_max_age: 21
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 25
, frm_part_max_ct: 200
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 30
, fte_parts_min_ct: 2
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 563
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Woodcamp"
, frm_price: 47
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "13:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 11
, frm_max_age: 14
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 12
, frm_part_max_ct: 25
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 10
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 564
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Dwingeloo"
, fld_led_id: 84
, frm_nm: "Zwerfhike"
, frm_price: 42
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "13:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 16
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 86
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 537
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Adventure Trail"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 14
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 41
, frm_max_outof_group: 10
, fte_teams_min_ct: 0
, fte_teams_max_ct: 20
, fte_parts_min_ct: 2
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 548
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "AppTrail 4.0"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "11:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 16
, frm_max_age: 19
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 75
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 543
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Groepshike"
, frm_price: 52
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "10:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 17
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 30
, frm_part_max_ct: 50
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 8
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 541
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "HIK (Hike Interesse Kamp)"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 10
, frm_max_age: 14
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 26
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 549
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Kokkamp"
, frm_price: 47
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 16
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 40
, frm_part_max_ct: 50
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 544
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Koninklijke Survival Expeditie Harderwijk"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "11:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "16:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 16
, frm_max_age: 32
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 12
, frm_part_max_ct: 40
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 551
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "LAN HIT"
, frm_price: 47
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 14
, frm_max_age: 17
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 20
, frm_max_outof_group: 5
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 0
, fte_parts_max_ct: 0
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 547
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Op zoek naar.."
, frm_price: 52
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 7
, frm_max_age: 11
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 30
, frm_max_outof_group: 5
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 0
, fte_parts_max_ct: 0
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 546
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Pio-Extreme"
, frm_price: 57
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "16:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 16
, frm_max_age: 19
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 30
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 30
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 545
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Piokamp"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 11
, frm_max_age: 15
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 20
, frm_part_max_ct: 40
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 30
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 538
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Ruiterkamp"
, frm_price: 72
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 16
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 12
, frm_part_max_ct: 16
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 3
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 540
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Ruiterkamp Gevorderden"
, frm_price: 72
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 16
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 8
, frm_part_max_ct: 8
, frm_max_outof_group: 2
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 2
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 536
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "TecHIT"
, frm_price: 52
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 10
, frm_max_age: 14
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 24
, frm_part_max_ct: 30
, frm_max_outof_group: 3
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 3
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 550
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Witte gij’t"
, frm_price: 57
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "16:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 18
, frm_max_age: 30
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 40
, frm_max_outof_group: 14
, fte_teams_min_ct: 0
, fte_teams_max_ct: 40
, fte_parts_min_ct: 1
, fte_parts_max_ct: 8
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 542
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Woudlopershike"
, frm_price: 42
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "16:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 17
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 20
, frm_part_max_ct: 50
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 10
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 539
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Harderwijk"
, fld_led_id: 85
, frm_nm: "Zeilhit"
, frm_price: 62
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 20
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "17:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 11
, frm_max_age: 15
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 18
, frm_part_max_ct: 26
, frm_max_outof_group: 4
, fte_teams_min_ct: 0
, fte_teams_max_ct: 6
, fte_parts_min_ct: 0
, fte_parts_max_ct: 0
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 566
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "Accra Express"
, frm_price: 37
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "12:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 8
, frm_max_age: 88
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 10
, frm_part_max_ct: 20
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 1
, fte_modulo: 1
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 512
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "Breinbrekers On Tour"
, frm_price: 57
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "10:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "14:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 25
, frm_max_age: 88
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 20
, frm_part_max_ct: 40
, frm_max_outof_group: 0
, fte_teams_min_ct: 0
, fte_teams_max_ct: 20
, fte_parts_min_ct: 2
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 508
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "Deutschland Dropping Race"
, frm_price: 52
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "10:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 14
, frm_max_age: 17
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 18
, frm_part_max_ct: 42
, frm_max_outof_group: 8
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 506
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "Eifel 50° Noord - the Meltdown"
, frm_price: 72
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "09:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 15
, frm_max_age: 18
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 20
, frm_part_max_ct: 40
, frm_max_outof_group: 10
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 2
, fte_parts_max_ct: 5
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 509
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "InterHITy"
, frm_price: 57
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "11:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "14:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 18
, frm_max_age: 30
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 16
, frm_part_max_ct: 32
, frm_max_outof_group: 6
, fte_teams_min_ct: 0
, fte_teams_max_ct: 10
, fte_parts_min_ct: 2
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 514
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "Kokkamp-Xtreme"
, frm_price: 67
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "14:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 16
, frm_max_age: 88
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 25
, frm_max_outof_group: 5
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 5
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 513
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "Make Your Choice"
, frm_price: 47
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "19:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "14:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 14
, frm_max_age: 17
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 25
, frm_part_max_ct: 45
, frm_max_outof_group: 8
, fte_teams_min_ct: 0
, fte_teams_max_ct: 25
, fte_parts_min_ct: 2
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 507
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "Powerkids HIT-it"
, frm_price: 52
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "12:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "14:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 7
, frm_max_age: 11
, frm_min_age_margin_days: 0
, frm_max_age_margin_days: 90
, frm_part_min_ct: 24
, frm_part_max_ct: 32
, frm_max_outof_group: 6
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 505
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Mook"
, fld_led_id: 88
, frm_nm: "Stookkamp"
, frm_price: 47
, frm_from_dt_day: 18
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "18:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "21:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 10
, frm_max_age: 14
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 30
, frm_part_max_ct: 41
, frm_max_outof_group: 10
, fte_teams_min_ct: 0
, fte_teams_max_ct: 0
, fte_parts_min_ct: 1
, fte_parts_max_ct: 3
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 535
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Zeeland"
, fld_led_id: 87
, frm_nm: "Bourgondische Autopuzzeltocht"
, frm_price: 52
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "11:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "15:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 25
, frm_max_age: 65
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 35
, frm_part_max_ct: 50
, frm_max_outof_group: 20
, fte_teams_min_ct: 0
, fte_teams_max_ct: 25
, fte_parts_min_ct: 1
, fte_parts_max_ct: 4
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 533
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Zeeland"
, fld_led_id: 87
, frm_nm: "Game Time"
, frm_price: 47
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "10:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "16:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 10
, frm_max_age: 13
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 50
, frm_max_outof_group: 20
, fte_teams_min_ct: 0
, fte_teams_max_ct: 30
, fte_parts_min_ct: 1
, fte_parts_max_ct: 6
, fte_modulo: 0
},
{ kampinfo_project_jaar: 2014
, kampinfo_camp_id: 534
, kampinfo_project_evenement_id: 4106
, frm_cancel_dt1_day: 1
, frm_cancel_dt1_month: "maart"
, frm_cancel_dt1_year: 2014
, frm_cancel_dt2_day: 1
, frm_cancel_dt2_month: "maart"
, frm_cancel_dt2_year: 2014
, kampinfo_project_inningsdatum_day: 8
, kampinfo_project_inningsdatum_month: "maart"
, kampinfo_project_inningsdatum_year: 2014
, frm_location_nm: "Zeeland"
, fld_led_id: 87
, frm_nm: "Waar rook is ... is vuur"
, frm_price: 47
, frm_from_dt_day: 19
, frm_from_dt_month: "april"
, frm_from_dt_year: 2014
, frm_from_time: "09:00"
, frm_till_dt_day: 21
, frm_till_dt_month: "april"
, frm_till_dt_year: 2014
, frm_till_time: "16:00"
, frm_book_from_dt_day: 2
, frm_book_from_dt_month: "januari"
, frm_book_from_dt_year: 2014
, frm_book_till_dt_day: 1
, frm_book_till_dt_month: "maart"
, frm_book_till_dt_year: 2014
, frm_min_age: 12
, frm_max_age: 14
, frm_min_age_margin_days: 90
, frm_max_age_margin_days: 90
, frm_part_min_ct: 15
, frm_part_max_ct: 40
, frm_max_outof_group: 10
, fte_teams_min_ct: 0
, fte_teams_max_ct: 30
, fte_parts_min_ct: 1
, fte_parts_max_ct: 3
, fte_modulo: 0
},
]