[
{"kamp": "Alphen Team X-perience", "shantiid": 16319},
{"kamp": "Bear Gryllz HIT", "shantiid": 16320},
{"kamp": "GPS-hike (Grote Paas Speurtocht)", "shantiid": 16321},
{"kamp": "Het E.E.J.E.H.-Kamp", "shantiid": 16322},
{"kamp": "Kamp Culinair", "shantiid": 16323},
{"kamp": "Mega Geocache HIT", "shantiid": 16324},
{"kamp": "CSI: Crime Scout Investigation", "shantiid": 16327},
{"kamp": "Do, Dare & Deal with it! goes Pirates", "shantiid": 16328},
{"kamp": "Money Talks", "shantiid": 16329},
{"kamp": "Niet Zomaar Een HIT", "shantiid": 16330},
{"kamp": "Ouder-Kind-Hike Baarn", "shantiid": 16331},
{"kamp": "Welp-Ouder-Avonturenkamp", "shantiid": 16332},
{"kamp": "Wie is de Mol?", "shantiid": 16333},
{"kamp": "Adventure Rangers", "shantiid": 16334},
{"kamp": "Beginnershike", "shantiid": 16335},
{"kamp": "Brownsea Camp", "shantiid": 16336},
{"kamp": "Expeditie Dwingeloo", "shantiid": 16337},
{"kamp": "Happyhike", "shantiid": 16338},
{"kamp": "Jongerenhike", "shantiid": 16339},
{"kamp": "Junior Zwerfhike", "shantiid": 16340},
{"kamp": "Kokkamp", "shantiid": 16341},
{"kamp": "Ouder-Kind-Hike Dwingeloo", "shantiid": 16342},
{"kamp": "Trapperskamp", "shantiid": 16343},
{"kamp": "Triathike", "shantiid": 16344},
{"kamp": "Vrije Zwerfhike", "shantiid": 16345},
{"kamp": "Woodcamp", "shantiid": 16346},
{"kamp": "Zwerfhike", "shantiid": 16347},
{"kamp": "AppTrail 5.0", "shantiid": 16348},
{"kamp": "Bouwen & Bikken", "shantiid": 16349},
{"kamp": "GeocacheHIT", "shantiid": 16350},
{"kamp": "Groepshike - Cosa Nostra", "shantiid": 16351},
{"kamp": "HIK (Hike Interesse Kamp)", "shantiid": 16352},
{"kamp": "Hoe Overleef Ik?!", "shantiid": 16353},
{"kamp": "Koninklijke Survival Expeditie Harderwijk", "shantiid": 16354},
{"kamp": "Kookkamp", "shantiid": 16355},
{"kamp": "L.A.R.P. HIT", "shantiid": 16356},
{"kamp": "LAN HIT", "shantiid": 16357},
{"kamp": "Ouder-Kind-Hike Harderwijk", "shantiid": 16358},
{"kamp": "Pats boem! Exploratie HIT", "shantiid": 16359},
{"kamp": "Pio-Extreme", "shantiid": 16360},
{"kamp": "Piokamp", "shantiid": 16361},
{"kamp": "Ruiterkamp", "shantiid": 16362},
{"kamp": "Ruiterkamp Gevorderden", "shantiid": 16363},
{"kamp": "W.O.E.H.: Welpen Op Expeditie Harderwijk", "shantiid": 16364},
{"kamp": "Woudlopershike", "shantiid": 16365},
{"kamp": "BeverHIT 1 (zo-ma)", "shantiid": 16366},
{"kamp": "Deutschland Dropping Race 2.0", "shantiid": 16367},
{"kamp": "En da's állemaal in de Eifel gebeurd?!", "shantiid": 16368},
{"kamp": "InterHITy", "shantiid": 16369},
{"kamp": "Powerkids HIT-it", "shantiid": 16370},
{"kamp": "Stookkamp", "shantiid": 16371},
{"kamp": "Sweden Express", "shantiid": 16372},
{"kamp": "The Paranoia Project", "shantiid": 16373},
{"kamp": "ZeilHIT", "shantiid": 16374},
{"kamp": "Bourgondische Autopuzzeltocht", "shantiid": 16375},
{"kamp": "Game Time - Expeditie Robinson", "shantiid": 16376},
{"kamp": "Ouder-Welp-Hike", "shantiid": 16377},
{"kamp": "TeCoHIT", "shantiid": 16378},
{"kamp": "Treasure Hunt", "shantiid": 16379},
{"kamp": "Waar rook is ... is vuur", "shantiid": 16380},
{"kamp": "Alphen Hakt!", "shantiid": 16318},
{"kamp": "Ouder-Kind-Hike Alphen", "shantiid": 16325},
{"kamp": "The Junior Challenge", "shantiid": 16326},
]
